# MCP OAuth Gateway Configuration

# Gateway settings
host: "0.0.0.0"
port: 8080
issuer: "http://localhost:8080"
session_secret: "your-production-secret-key-change-this"
debug: true

# CORS configuration
cors:
  allow_origins: ["*"]         # Allowed origins (use specific domains in production)
  allow_credentials: true      # Allow credentials in CORS requests
  allow_methods:               # Allowed HTTP methods
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers: ["*"]         # Allowed headers (use specific headers in production)

# OAuth providers for user authentication
oauth_providers:  
  github:
    client_id: "${GITHUB_CLIENT_ID}"
    client_secret: "${GITHUB_CLIENT_SECRET}"
    scopes:
      - "user:email"

# MCP services to proxy
mcp_services:
  calculator:
    name: "Calculator Service"
    url: "http://localhost:3001/mcp"
    oauth_provider: "github"
    auth_required: true
    scopes:
      - "read"
      - "calculate"
    timeout: 30000
  

  calculator_public:
    name: "Public Calculator Service"
    url: "http://localhost:3001/mcp"
    auth_required: false
    timeout: 10000